# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBz3fxi8T5-o7cqipejG_4QOKMWZCcGR

To-Do List Application
"""

def show_menu():
    print("\n=== To-Do List Menu ===")
    print("1. View all tasks")
    print("2. Add a new task")
    print("3. Mark task as completed")
    print("4. Delete a task")
    print("5. Exit")

def view_tasks(tasks):
    if not tasks:
        print("\nNo tasks in your To-Do list!")
        return
    print("\nYour Tasks:")
    for idx, task in enumerate(tasks, start=1):
        status = "✓" if task['completed'] else "✗"
        print(f"{idx}. [{status}] {task['task']}")

def add_task(tasks):
    task_name = input("Enter the task: ").strip()
    if task_name:  # prevent empty tasks
        tasks.append({'task': task_name, 'completed': False})
        print(f"Task '{task_name}' added!")
    else:
        print("Task cannot be empty!")

def mark_completed(tasks):
    if not tasks:
        print("No tasks to mark as completed.")
        return
    view_tasks(tasks)
    try:
        task_num = int(input("Enter task number to mark as completed: "))
        if 1 <= task_num <= len(tasks):
            tasks[task_num - 1]['completed'] = True
            print(f"Task '{tasks[task_num - 1]['task']}' marked as completed!")
        else:
            print("Invalid task number!")
    except ValueError:
        print("Please enter a valid number!")

def delete_task(tasks):
    if not tasks:
        print("No tasks to delete.")
        return
    view_tasks(tasks)
    try:
        task_num = int(input("Enter task number to delete: "))
        if 1 <= task_num <= len(tasks):
            removed_task = tasks.pop(task_num - 1)
            print(f"Task '{removed_task['task']}' deleted!")
        else:
            print("Invalid task number!")
    except ValueError:
        print("Please enter a valid number!")

def main():
    tasks = []
    while True:
        show_menu()
        choice = input("Enter your choice (1-5): ").strip()
        if choice == '1':
            view_tasks(tasks)
        elif choice == '2':
            add_task(tasks)
        elif choice == '3':
            mark_completed(tasks)
        elif choice == '4':
            delete_task(tasks)
        elif choice == '5':
            print("Exiting To-Do List Application. Goodbye!")
            break
        else:
            print("Invalid choice! Please select from 1-5.")

if __name__ == "__main__":
    main()

